export const content = {
  tr: {
    welcome: "Hoş Geldiniz",
    signIn: "Giriş Yap",
    signUp: "Kayıt Ol",
    signUpDescription: "E-posta ile kayıt olun veya Google ile devam edin.",
    signInDescription: "E-posta ile giriş yapın veya Google ile devam edin.",
    fullName: "İsim Soyisim",
    email: "E-posta",
    password: "Şifre",
    passwordConfirm: "Şifre Tekrar",
    passwordsDoNotMatch: "Şifreler eşleşmiyor.",
    registrationError: "Kayıt hatası",
    alreadyHaveAccount: "Zaten bir hesabın var mı?",
    forgotPassword: "Şifreni mi unuttun?",
    sendResetLink: "Sıfırlama linki gönder",
    resetPassword: "Şifre Sıfırlama",
    resetPasswordInstructions: "E-posta adresini gir, sana bir sıfırlama bağlantısı gönderelim.",
    newPassword: "Yeni Şifre",
    newPasswordConfirm: "Yeni Şifre Tekrar",
    updatePassword: "Şifreyi Güncelle",
    passwordResetSuccess: "Şifre başarıyla güncellendi. Giriş sayfasına yönlendiriliyorsunuz...",
    passwordResetError: "Şifre güncellenemedi",
     passwordResetLinkSent: "Şifre sıfırlama bağlantısı e-posta adresine gönderildi.",
resetPasswordDesc: "E-posta adresini gir, sana bir sıfırlama bağlantısı gönderelim.",
    verifyEmailTitle: "📩 E-posta Doğrulama",
    verifyEmailInstruction: "Kayıt işlemini tamamlamak için e-posta adresine gönderilen bağlantıya tıkla.",
    verifyEmailNote: "Doğrulama bağlantısına tıkladıktan sonra giriş yapabilirsin.",
    signInWithGoogle: "Google ile giriş yap",
    signInWithFacebook: "Facebook ile giriş yap",
    loginFailed: "Giriş başarısız",
    registrationSuccess: "Kayıt başarılı",
    loadingRedirectMessage: "Giriş tamamlanıyor, lütfen bekleyin...",
    noAccount: "Hesabın yok mu?",
    portfolioValue: "Portföy Değeri",
    manageFinancialFuture: "Finansal Geleceğinizi Yönetin",
    trackInvestments: "PortfoyPro ile yatırımlarınızı takip edin, analiz edin ve finansal hedeflerinize ulaşın.",
    portfolioSummary: "Portföy Özeti",
    assetDistribution: "Varlık Dağılımı",
    recentTransactions: "Son İşlemler",
    asset: "Varlık",
    transaction: "İşlem",
    amount: "Miktar",
    date: "Tarih",
    whyPortfoyPro: "Neden PortfoyPro?",
    realTimeTracking: "Gerçek Zamanlı Takip",
    realTimeTrackingDesc: "Tüm yatırımlarınızı tek bir platformda gerçek zamanlı olarak takip edin. Hisse senetleri, kripto paralar, fonlar ve daha fazlası.",
    smartPortfolioAnalysis: "Akıllı Portföy Analizi",
    smartPortfolioAnalysisDesc: "Gelişmiş analiz araçlarıyla portföyünüzün performansını değerlendirin, risk analizini görün ve daha bilinçli yatırım kararları alın.",
    secureAndPrivate: "Güvenli ve Özel",
    secureAndPrivateDesc: "Verileriniz en yüksek güvenlik standartlarıyla korunur. Hesap bilgileriniz ve finansal verileriniz her zaman güvende kalır.",
    shapeFinancialFuture: "Finansal Geleceğinizi Bugün Şekillendirin",
    startManagingInvestments: "PortfoyPro ile yatırımlarınızı yönetmeye hemen başlayın ve finansal hedeflerinize daha hızlı ulaşın.",
    startFree: "Hemen Ücretsiz Başlayın",
    quickLinks: "Hızlı Bağlantılar",
    resources: "Kaynaklar",
    legal: "Yasal",
    about: "Hakkımızda",
    buy: "Alış",
    sell: "Satış",
    stocks: "Hisse Senetleri",
    crypto: "Kripto",
    bonds: "Tahvil/Bono",
    gold: "Altın",
    cash: "Nakit",
    features: "Özellikler",
    pricing: "Fiyatlandırma",
    contact: "İletişim",
    blog: "Blog",
    guides: "Rehberler",
    faq: "SSS",
    support: "Destek",
    privacyPolicy: "Gizlilik Politikası",
    termsOfUse: "Kullanım Şartları",
    cookiePolicy: "Çerez Politikası",
    kvkk: "KVKK",
    disclaimer: "Yasal Uyarılar",
    footerText: "2024 PortfoyPro. Tüm hakları saklıdır.",
   

  },
  en: {
    welcome: "Welcome",
    signIn: "Sign In",
    signUp: "Sign Up",
    signUpDescription: "Sign up with email or continue with Google.",
    signInDescription: "Sign in with email or continue with Google.",
    fullName: "Full Name",
    email: "Email",
    password: "Password",
    passwordConfirm: "Confirm Password",
    passwordsDoNotMatch: "Passwords do not match.",
    registrationError: "Registration error",
    alreadyHaveAccount: "Already have an account?",
    forgotPassword: "Forgot your password?",
    sendResetLink: "Send Reset Link",
    resetPassword: "Password Reset",
    resetPasswordInstructions: "Enter your email, we will send you a reset link.",
    newPassword: "New Password",
    newPasswordConfirm: "Confirm New Password",
    updatePassword: "Update Password",
    passwordResetSuccess: "Password updated successfully. Redirecting to login...",
    passwordResetError: "Password could not be updated",
    verifyEmailTitle: "📩 Email Verification",
    passwordResetLinkSent: "Password reset link has been sent to your email address.",
resetPasswordDesc: "Enter your email address, and we will send you a reset link.",

    verifyEmailInstruction: "To complete your registration, click the link sent to your email address.",
    verifyEmailNote: "You can log in after clicking the verification link.",
    signInWithGoogle: "Sign in with Google",
    signInWithFacebook: "Sign in with Facebook",
    loginFailed: "Login failed",
    registrationSuccess: "Registration successful",
    loadingRedirectMessage: "Completing login, please wait...",
    noAccount: "Don't have an account?",
    portfolioValue: "Portfolio Value",
    manageFinancialFuture: "Manage Your Financial Future",
    trackInvestments: "Track, analyze, and achieve your financial goals with PortfoyPro.",
    portfolioSummary: "Portfolio Summary",
    assetDistribution: "Asset Distribution",
    recentTransactions: "Recent Transactions",
    asset: "Asset",
    transaction: "Transaction",
    amount: "Amount",
    date: "Date",
    whyPortfoyPro: "Why PortfoyPro?",
    realTimeTracking: "Real-Time Tracking",
    realTimeTrackingDesc: "Track all your investments in real-time on a single platform. Stocks, cryptocurrencies, funds, and more.",
    smartPortfolioAnalysis: "Smart Portfolio Analysis",
    smartPortfolioAnalysisDesc: "Evaluate your portfolio's performance with advanced analysis tools, see risk analysis, and make more informed investment decisions.",
    secureAndPrivate: "Secure and Private",
    secureAndPrivateDesc: "Your data is protected with the highest security standards. Your account information and financial data are always safe.",
    shapeFinancialFuture: "Shape Your Financial Future Today",
    startManagingInvestments: "Start managing your investments with PortfoyPro today and reach your financial goals faster.",
    startFree: "Start Free Now",
    quickLinks: "Quick Links",
    resources: "Resources",
    legal: "Legal",
    about: "About",
    buy: "Buy",
    sell: "Sell",
    stocks: "Stocks",
    crypto: "Crypto",
    bonds: "Bonds",
    gold: "Gold",
    cash: "Cash",
    features: "Features",
    pricing: "Pricing",
    contact: "Contact",
    blog: "Blog",
    guides: "Guides",
    faq: "FAQ",
    support: "Support",
    privacyPolicy: "Privacy Policy",
    termsOfUse: "Terms of Use",
    cookiePolicy: "Cookie Policy",
    kvkk: "KVKK",
    disclaimer: "Disclaimer",
    footerText: "2024 PortfoyPro. All rights reserved.",
  },
} as const;
